//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/3ClipseGame/Steam/Entities/Player/Scripts/PlayerStateMachine/Input/MovementInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MovementInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MovementInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MovementInput"",
    ""maps"": [
        {
            ""name"": ""ExploreStateActionMap"",
            ""id"": ""8a061ef1-fe18-40ab-97b8-7292b75415a3"",
            ""actions"": [
                {
                    ""name"": ""Walk"",
                    ""type"": ""Value"",
                    ""id"": ""eb63dac8-0c27-4702-9098-9db0d71777ed"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""0def7729-3466-407b-bec4-cb0b0520919d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""a90d34f9-30f8-4e43-af36-0a3d5d000be9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""ef04a0fd-8318-4920-a0bd-0c5a7130521e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""4a941e43-9324-413c-89a0-a41dd8e8f561"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8a98128f-ca43-4284-90af-43fcf9181d6d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""25daae04-4ebe-49af-982c-bf20d96647eb"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f0dfdeff-5a1a-4639-87c4-78e841753328"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b5615355-ab03-4dc2-848c-c1a2320014da"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ed638d5d-cbf3-4616-82dd-d5cf9c8af26f"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f0d4885-884d-470e-ada3-cc771064a9c4"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f9d41cb-ad55-495b-aeaa-eae81d0bd466"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ExploreStateActionMap
        m_ExploreStateActionMap = asset.FindActionMap("ExploreStateActionMap", throwIfNotFound: true);
        m_ExploreStateActionMap_Walk = m_ExploreStateActionMap.FindAction("Walk", throwIfNotFound: true);
        m_ExploreStateActionMap_Run = m_ExploreStateActionMap.FindAction("Run", throwIfNotFound: true);
        m_ExploreStateActionMap_Crouch = m_ExploreStateActionMap.FindAction("Crouch", throwIfNotFound: true);
        m_ExploreStateActionMap_Jump = m_ExploreStateActionMap.FindAction("Jump", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ExploreStateActionMap
    private readonly InputActionMap m_ExploreStateActionMap;
    private IExploreStateActionMapActions m_ExploreStateActionMapActionsCallbackInterface;
    private readonly InputAction m_ExploreStateActionMap_Walk;
    private readonly InputAction m_ExploreStateActionMap_Run;
    private readonly InputAction m_ExploreStateActionMap_Crouch;
    private readonly InputAction m_ExploreStateActionMap_Jump;
    public struct ExploreStateActionMapActions
    {
        private @MovementInput m_Wrapper;
        public ExploreStateActionMapActions(@MovementInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Walk => m_Wrapper.m_ExploreStateActionMap_Walk;
        public InputAction @Run => m_Wrapper.m_ExploreStateActionMap_Run;
        public InputAction @Crouch => m_Wrapper.m_ExploreStateActionMap_Crouch;
        public InputAction @Jump => m_Wrapper.m_ExploreStateActionMap_Jump;
        public InputActionMap Get() { return m_Wrapper.m_ExploreStateActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ExploreStateActionMapActions set) { return set.Get(); }
        public void SetCallbacks(IExploreStateActionMapActions instance)
        {
            if (m_Wrapper.m_ExploreStateActionMapActionsCallbackInterface != null)
            {
                @Walk.started -= m_Wrapper.m_ExploreStateActionMapActionsCallbackInterface.OnWalk;
                @Walk.performed -= m_Wrapper.m_ExploreStateActionMapActionsCallbackInterface.OnWalk;
                @Walk.canceled -= m_Wrapper.m_ExploreStateActionMapActionsCallbackInterface.OnWalk;
                @Run.started -= m_Wrapper.m_ExploreStateActionMapActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_ExploreStateActionMapActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_ExploreStateActionMapActionsCallbackInterface.OnRun;
                @Crouch.started -= m_Wrapper.m_ExploreStateActionMapActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_ExploreStateActionMapActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_ExploreStateActionMapActionsCallbackInterface.OnCrouch;
                @Jump.started -= m_Wrapper.m_ExploreStateActionMapActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_ExploreStateActionMapActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_ExploreStateActionMapActionsCallbackInterface.OnJump;
            }
            m_Wrapper.m_ExploreStateActionMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Walk.started += instance.OnWalk;
                @Walk.performed += instance.OnWalk;
                @Walk.canceled += instance.OnWalk;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
            }
        }
    }
    public ExploreStateActionMapActions @ExploreStateActionMap => new ExploreStateActionMapActions(this);
    public interface IExploreStateActionMapActions
    {
        void OnWalk(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
    }
}
